spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/surveillance-pseudonym
    username: ars-pseudo-user
    password: Vivv+zuujLGkfYzO6hfFCw==

  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ars-pseudo-ddl
    password: wCriidPTKToyPetNzOR2eA==
    parameters:
      db-user-service: ${spring.datasource.username}
      db-user-purger: ars-pseudo-purger

logging:
  level:
    de.gematik.demis.surveillance.pseudonym: DEBUG
    org:
      hibernate:
        SQL: DEBUG
#        orm.jdbc.bind: trace

sps:
  hash:
    pepper: 36EWaW1l4MBwORh39aaLzT9rVqF9wD3QtE4jltq8NKk=
  period:
    max-lifetime-in-years: 3
    # format: --MM-dd
    adjust-reference-day: --01-01

feature:
  flag:
    individual_pseudonym: true