{{/* Check required values and define variables */}}
{{- $dockerRepository := .Values.required.image.repository | required ".Values.required.image.repository is required." -}}
{{- $dockerImage := .Values.required.image.name | required ".Values.required.image.name is required." -}}
{{- $dockerTag := .Values.required.image.tag | default .Chart.AppVersion -}}
{{- $customEnvVars := .Values.customEnvVars -}}
{{- $entrypointString := toString .Values.application.entrypoint | trimPrefix "[" | trimSuffix "]" -}}
{{- $cmdParamsString := toString .Values.application.parameters | trimPrefix "[" | trimSuffix "]" -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "surveillance-pseudonym-purger.fullversionname" . }}
  labels:
    {{- include "surveillance-pseudonym-purger.labels" . | nindent 4 }}
    {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  schedule: {{ .Values.cronJobSchedule | required ".Values.cronJobSchedule is required." }}
  suspend: {{ .Values.required.suspend | required ".Values.required.suspend is required." }}
  # Replaces the currently running job run with a new job run
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            {{- include "surveillance-pseudonym-purger.labels" . | nindent 12 }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: tmp-volume
              emptyDir: {}
          {{- if .Values.debug.enable }}
            - name: jfr-volume
              emptyDir: {}
          {{- end }}
            - name: secret-volume
              secret:
                secretName: {{ .Values.secret.name }}
                items:
                  - key: {{ .Values.secret.key }}
                    path: {{ .Values.secret.propPath }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "surveillance-pseudonym-purger.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: "{{ .Chart.Name }}"
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ $dockerRepository }}/{{ $dockerImage }}:{{ $dockerTag }}"
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            {{- /* Configure entrypoint and parameters */ -}}
            {{- if .Values.istio.enable }}
            command: [ "/bin/sh" ]
            {{- else }}
            {{- with .Values.application.entrypoint }}
            command:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- end }}
            {{- if .Values.istio.enable }}
            args: [ "-c", "until wget -q -O- --spider --tries=1 http://localhost:{{ .Values.istio.healthPort }}/healthz/ready; do echo \"Waiting for Sidecar...\"; sleep 3; done; echo \"Sidecar available. Running the command...\"; {{ print $entrypointString }} {{ print $cmdParamsString }} ; x=$?; echo \"### Return Code: $x\" ; if [ $x -eq 0 ]; then wget -q --post-data='' --tries=1 -O /dev/null http://localhost:{{ .Values.istio.quitPort }}/quitquitquit; fi; exit $x" ]
            {{- else }}
            {{- with .Values.application.parameters }}
            args:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- end }}
            volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            {{- if .Values.debug.enable }}
            - name: jfr-volume
              mountPath: /jfrdump
            {{- end }}
            - name: secret-volume
              readOnly: true
              mountPath: "/secrets/dbPassword"
            # Set the Environment Variables for the container
            env:
              - name: "TZ"
                value: "Europe/Berlin"
              {{- if .Values.debug.enable }}
              - name: "JAVA_TOOL_OPTIONS"
                value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9000"
              {{- end }}
              # Set Spring Configuration Import from Folder Structure
              - name: "SPRING_CONFIG_IMPORT"
                value: "optional:configtree:/secrets/*/"
              {{- if $customEnvVars }}
              # Custom Environment Variables
              {{- range $_, $key := keys $customEnvVars | sortAlpha }}
              - name: {{ $key | quote }}
                value: {{ get $customEnvVars $key | quote }}
              {{- end }}
              {{- end }}
            {{- if .Values.debug.enable }}
            # Define Debug Port
            ports:
              - name: debug-port
                containerPort: 9000
                protocol: TCP
            {{- end }}
            {{- with .Values.resources }}
            # Define Limits and Requested Resources (CPU/RAM)
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
