fullnameOverride: surveillance-pseudonym-service
service:
  type: ClusterIP
  ports:
    http: 8080
istio:
  enable: true
  virtualService:
    gateways: {}
    http:
      match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      timeout: 5s
      retries:
        enable: true
        attempts: 1
    hosts: {}
  subsets:
    main:
      version: 1.0.0
      weight: "100"
# activate Traffic mirroring, also called shadowing with the following lines
#      mirror:
#        version: 1.1.0
#        mirrorPercentage: 0
